name: Publication du site

on:
  schedule:
    # Tous les lundis à 00h10, heure française
    - cron: "10 0 * * 1"
      timezone: "Europe/Paris"

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "publication"
  cancel-in-progress: false

jobs:
  publication:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Mettre à jour main avec develop
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin

          git checkout main
          git reset --hard origin/main

          git merge origin/develop --no-edit

          git push origin main

      - name: Récupérer main après publication
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 1

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v5

      - name: Envoyer le site à GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: .

      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
